name=NodeLib-ANCS
version=1.0.0
author=ASTROLAB <xxap2005@outlook.com>
maintainer=ASTROLAB <xxap2005@outlook.com>
sentence=ESP32 ANCS Library for NodeLib
paragraph=Apple Notification Center Service Library for ESP32
category=Communication
url=https://github.com/EVGA2048/NodeLib.git
architectures=esp32
includes=src/NodeLib_ANCS.h